### PR TITLE
REQ-55 Can now update Hold Request Service with Patch Request

### PR DESCRIPTION
**Pull request by holingpoon**
This code should
1. Update Hold Request Service **first**, updating status of `processed` and `success` by `HoldRequestId`
2. Proceed with assembling data for e-mail notification
Please review. Thanks!

### CODE REVIEW

**Review by rhernand3z — COMMENTED** [review]
Is there any checks to the arguments in patchHoldRequestById method? In the event they are not set/undefined?

**Comment by holingpoon** [comment]
@rhernand3z APIExceptions are now included for `HoldRequestClient` class. Exception handling for `Listener` will be on subsequent PRs. Thanks!

**Review by rhernand3z — APPROVED** [review]
Looks good.

**Comment by kfriedman** [comment]
Nice work. Some thoughts:

- You might want to avoid use of `if/else` statements and try to refactor into separate methods.
- You might want to break up the `process` method into multiple methods for clarity (i.e. try to have a method do one thing).
- I think we agreed that we will log errors with `holdRequestId`.
- You might want to start thinking about what errors are "retryable" and what errors are "acceptable" and should just be logged.

**Pull request merged**
